import type { OneShotPacket, Scene } from "@oneshotsmith/core";

// Markdown export for prep tools (Obsidian, Notion, plain text editors).

function sceneToMarkdown(scene: Scene): string {
  const lines: string[] = [`## ${scene.key}. ${scene.title}`, ""];
  lines.push(`*${scene.type} · ~${scene.minutes} min${scene.cuttable ? " · cuttable" : ""}*`, "");
  if (scene.readAloud) {
    lines.push(`> **Read aloud:** ${scene.readAloud}`, "");
  }
  lines.push(scene.summary, "");
  for (const d of scene.details) lines.push(`- ${d}`);
  lines.push("");
  if (scene.skillChallenge) {
    lines.push(`**Skill challenge.** ${scene.skillChallenge.description}`);
    for (const c of scene.skillChallenge.checks) {
      lines.push(`- DC ${c.dc} ${c.skill} — ${c.use}`);
    }
    lines.push(`- **Success:** ${scene.skillChallenge.success}`);
    lines.push(`- **Failure:** ${scene.skillChallenge.failure}`, "");
  }
  if (scene.encounter) {
    const e = scene.encounter;
    lines.push(
      `**Encounter** (adjusted ${e.adjustedXP.toLocaleString()} XP vs. budget ${e.budget.toLocaleString()}, ×${e.multiplier}):`
    );
    lines.push("", "| Creature | CR | AC | HP | Attack | XP |", "|---|---|---|---|---|---|");
    for (const g of e.groups) {
      lines.push(
        `| ${g.count > 1 ? `${g.count} × ` : ""}${g.monster.name} | ${g.monster.cr} | ${g.monster.ac} | ${g.monster.hp} | ${g.monster.attack} | ${(g.monster.xp * g.count).toLocaleString()} |`
      );
    }
    lines.push("", `- **Terrain:** ${e.terrain}`, `- **Tactics:** ${e.tactics}`, "");
  }
  if (scene.clue) lines.push(`> Clue planted here: ${scene.clue}`, "");
  return lines.join("\n");
}

export function packetToMarkdown(packet: OneShotPacket): string {
  const { input } = packet;
  const lines: string[] = [
    `# ${packet.title}`,
    "",
    `**Adventure Module ${packet.moduleCode}** — an adventure for ${input.partySize} characters of level ${input.level} (${input.theme}, ${input.difficulty}, ${input.timebox} session)`,
    "",
    `*${packet.tagline}*`,
    "",
    "## For the Game Master",
    "",
    packet.synopsis,
    "",
    "## The Hook",
    "",
    `> **Read aloud:** ${packet.hook.readAloud}`,
    "",
    packet.hook.summary,
    "",
    "If the party balks:",
    ...packet.hook.alternates.map((a) => `- ${a}`),
    "",
    `## The Site: ${packet.location.name}`,
    "",
    packet.location.description,
    "",
    "Map key:",
    ...packet.map.rooms.filter((r) => r.key > 0).map((r) => `${r.key}. ${r.label}`),
    "",
    `## The Villain: ${packet.villain.name} — ${packet.villain.epithet}`,
    "",
    `- **Motivation:** ${packet.villain.motivation}`,
    `- **Plan:** ${packet.villain.plan}`,
    `- **Secret:** ${packet.villain.secret}`,
    `- **At the table:** ${packet.villain.mannerism}`,
    `- **Stats:** ${packet.villain.stats.name} (CR ${packet.villain.stats.cr}) — AC ${packet.villain.stats.ac}, HP ${packet.villain.stats.hp}, ${packet.villain.stats.attack}`,
    "",
    "## The Cast",
    "",
    ...packet.npcs.flatMap((npc, i) => [
      `### ${npc.name}${i === 0 ? " (patron)" : ""}`,
      `${npc.ancestry} ${npc.occupation}. Looks: ${npc.appearance}. Manner: ${npc.mannerism}. Voice: ${npc.voice}.`,
      `Wants: ${npc.goal} Secret: ${npc.secret}`,
      "",
    ]),
    "# The Scenes",
    "",
    ...packet.scenes.map((s) => sceneToMarkdown(s)),
    "## Secrets & Clues",
    "",
    ...packet.clues.map((c) => `- [ ] ${c}`),
    "",
    `**The Twist.** ${packet.twist}`,
    "",
    "## Treasure",
    "",
    ...packet.treasure.parcels.map((t) => `- ${t}`),
    "",
    `**${packet.treasure.signatureItem.name}** (${packet.treasure.signatureItem.rarity}${packet.treasure.signatureItem.attunement ? ", requires attunement" : ""}). ${packet.treasure.signatureItem.description}`,
    "",
    "## Running the Table",
    "",
    "Session clock:",
    ...packet.pacing.map((p) => `- ${p.minutes} min — ${p.label}: ${p.note}`),
    "",
    `**Weaker table.** ${packet.scaling.weaker}`,
    "",
    `**Stronger table.** ${packet.scaling.stronger}`,
    "",
    "If running behind:",
    ...packet.cutList.map((c) => `- ${c}`),
    "",
    ...packet.tables.flatMap((t) => [
      `## ${t.title} (${t.die})`,
      "",
      ...t.entries.map((e, i) => `${i + 1}. ${e}`),
      "",
    ]),
    "---",
    "",
    `Generated by OneShotsmith · seed \`${input.seed}\` · includes material from the SRD 5.1 by Wizards of the Coast LLC, CC-BY-4.0`,
  ];
  return lines.join("\n");
}
